### ISSUE TITLE
Headers' keys get lowercased

### ISSUE THREAD

**Issue by markmssd** [lykmapipo/mock-express-request#10]
I have the following snippet:

```
const req = new MockExpressRequest({
      headers: {
        'X-Hub-Signature': 'invalid' // noticed the capital X, H, S
      }
    });
```
Then, when I `console.log(req.headers)`, I see that the header is now `x-hub-signature`. I think it should preserve their casing. What do you think?

**Comment by cmswalker** [comment]
The issue with that approach is that it is out of line with the API of [req.get](https://expressjs.com/en/4x/api.html#req.get)

headers should be lowercased in the header entity. You can access them irrelevant of case by using `req.get('X-Hub-Signature')` which will lowercase the lookup key and give you back the desired key.

Express doesn't support setting request headers in the same way as fetching request headers when you're accessing the `headers` object directly. If you'd like additional functionality you could try a package I made for explicitly setting incoming `req` headers. https://www.npmjs.com/package/request

**Comment by markmssd** [comment]
Thanks for your prompt response!

`req.get` did the trick and I switched to it, instead of using plain old `req.headers['X-Hub-Signature']`
