### ISSUE TITLE
Bump Version?

### ISSUE THREAD

**Issue by duereg** [lykmapipo/mock-express-request#5]
The version on npm (1.1) is out of date with the current code. Could you release a new version?

**Comment by duereg** [comment]
bump

**Comment by apsavin** [comment]
@lykmapipo?..

**Comment by apsavin** [comment]
@lykmapipo Are you still interested in this repo/npm package?

**Comment by lykmapipo** [comment]
@apsavin v0.2.0 published.

@apsavin I can accept you helping hand.

**Comment by physikerwelt** [comment]
@lykmapipo could you publish the new version on npm, thank you
 cf. https://gerrit.wikimedia.org/r/#/c/370603/22..24/package.json
