### ISSUE TITLE
Publish v0.2.1

### ISSUE THREAD

**Issue by physikerwelt** [lykmapipo/mock-express-request#9]
@lykmapipo could you please 
- [x] publish the current repo as v0.2.1 on [npm.js](https://www.npmjs.com/package/mock-express-request), 
- [x] thereafter update the dependency in the [response package](https://github.com/lykmapipo/mock-express-response/blob/master/package.json#L63), and 
- [x] [publish](https://www.npmjs.com/package/mock-express-response) the response package as v0.2.2 as well.

Thanks a lot.
CC @d00rman

**Comment by lykmapipo** [comment]
@physikerwelt On it.

**Comment by lykmapipo** [comment]
@physikerwelt check v0.2.2

**Comment by physikerwelt** [comment]
@lykmapipo thanks a lot. The security issues are [now resolved](https://integration.wikimedia.org/ci/job/npm-node-6-jessie/18598/console).
